"""Add weekday prep build targets

Revision ID: 609552584fae
Revises: a591f3bc39c6
Create Date: 2026-04-25 21:26:37.484675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609552584fae'
down_revision = 'a591f3bc39c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prep_template_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monday_build_to', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tuesday_build_to', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('wednesday_build_to', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('thursday_build_to', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('friday_build_to', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('saturday_build_to', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sunday_build_to', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prep_template_items', schema=None) as batch_op:
        batch_op.drop_column('sunday_build_to')
        batch_op.drop_column('saturday_build_to')
        batch_op.drop_column('friday_build_to')
        batch_op.drop_column('thursday_build_to')
        batch_op.drop_column('wednesday_build_to')
        batch_op.drop_column('tuesday_build_to')
        batch_op.drop_column('monday_build_to')

    # ### end Alembic commands ###
