"""Add prep coverage days

Revision ID: 80b31d459303
Revises: 609552584fae
Create Date: 2026-04-25 22:03:36.306467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b31d459303'
down_revision = '609552584fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prep_template_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prep_coverage_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prep_template_items', schema=None) as batch_op:
        batch_op.drop_column('prep_coverage_days')

    # ### end Alembic commands ###
