"""Add prep item rule fields

Revision ID: a591f3bc39c6
Revises: 
Create Date: 2026-04-25 20:15:23.682665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a591f3bc39c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prep_template_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_item_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('prep_unit', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('rounding_increment', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('minimum_build', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('buffer_percent', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('conversion_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prep_template_items', schema=None) as batch_op:
        batch_op.drop_column('conversion_notes')
        batch_op.drop_column('buffer_percent')
        batch_op.drop_column('minimum_build')
        batch_op.drop_column('rounding_increment')
        batch_op.drop_column('prep_unit')
        batch_op.drop_column('report_item_name')

    # ### end Alembic commands ###
